# Generated by Django 4.1 on 2022-08-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HatchingBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatch_date', models.DateField()),
                ('incubator', models.CharField(max_length=32)),
                ('rhode_island_red', models.IntegerField(default=0)),
                ('barred_plymouth_rock', models.IntegerField(default=0)),
                ('black_australorp', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hatch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='Models.hatchingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_done', models.BooleanField()),
                ('is_delivery', models.BooleanField()),
                ('shipping_fee', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('hatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='Models.hatchingbatch')),
            ],
        ),
    ]
