# Generated by Django 3.2.6 on 2022-08-16 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='barred_plymouth_rock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='black_australorp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rhode_island_red',
            field=models.IntegerField(default=0),
        ),
    ]
