# Generated by Django 3.2.6 on 2022-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_auto_20220816_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='remarks',
            field=models.CharField(default='', max_length=255),
        ),
    ]
